name: di_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  # networking
  retrofit: any
  logger: any
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0

  # state management
  flutter_bloc: ^8.1.3

  # di
  injectable: ^2.1.2
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # generator
  retrofit_generator: any
  build_runner: any
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
